# Generated by Django 5.2.4 on 2025-08-03 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_shift_ptorequest_weeklyschedule_lunchbreakoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('preferred_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.shift')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
